# Generated by Django 5.1.7 on 2025-03-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='model',
            new_name='name',
        ),
    ]
